import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { sanityClient, urlFor } from "../sanity";
import Img from 'next/image'

import Header from '../components/Header';
import Visibility from '../components/Visibility';
import Local from '../components/Local';
import Cost from '../components/Cost';
import Bright from '../components/Bright';
import Review from '../components/Review';



const headerQuery = `*[_type == "header"]{
  name, title, mainImage, secondTitle, referenceList,
}`;
const firstSectionQuery = `*[_type == "firstSection"]{
  name, referenceList, userImage, userName, userTitle
}`;
const secondSectionQuery = `*[_type == "secondSection"]{
  name,title,image,text
}`;
const thirdSectionQuery = `*[_type == "thirdSection"]{
  name,title,secondTitle,priceImage,featuresImage
}`;
const reviewQuery = `*[_type == "review"]{
  reviewImage,reviewQuot,reviewName,reviewAddress
}`;
const reviewImagesQuery = `*[_type == "reviewImages"]{
  referenceList
}`;


export default function Home({ header, firstSection, secondSection, thirdSection, review,reviewImages }) {
  console.log(reviewImages)

  // const { name, title, mainImage, secondTitle, referenceList, } = header[0]

  // const imageProps = useNextSanityImage(
  //   sanityClient,
  //   mainImage
  // );

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header header={header} />
      <Visibility firstSection={firstSection} />
      <Local secondSection={secondSection} />
      <Cost thirdSection={thirdSection} />
      <Bright />
      <Review review={review} reviewImages={reviewImages} />
    </div>
  )
}

export async function getStaticProps() {
  const header = await sanityClient.fetch(headerQuery,);
  const firstSection = await sanityClient.fetch(firstSectionQuery);
  const secondSection = await sanityClient.fetch(secondSectionQuery);
  const thirdSection = await sanityClient.fetch(thirdSectionQuery);
  const review = await sanityClient.fetch(reviewQuery);
  const reviewImages = await sanityClient.fetch(reviewImagesQuery);
  return { props: { header, firstSection, secondSection, thirdSection, review,reviewImages } };
}